[general]
use_config = true

#List settings
#Syntax: ["modid:block|weight"]
#Example: ["minecraft:stone|2","minecraft:dirt|1"]
#Forge tags are supported
[general.lists]
block_list_cobble = [
    "minecraft:cobblestone|1",
]

block_list_stone = [
    "minecraft:granite|1",
    "minecraft:diorite|1",
    "minecraft:andesite|1"
]

block_list_basalt = [
    "minecraft:basalt|1",
    "minecraft:blackstone|1",
    "minecraft:netherrack|1",
]

#Custom generators
#Syntax: [gen]
#Gen: [type, block, list]
#Type: cobblestone, stone
#Block: resource location of the block below the generated block
#List: see List settings
#Examples:
#custom_generators = [
#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
[general.lists.custom]
custom_generators = [
    [
        "cobblestone",
        "minecraft:amethyst_block",
        [
            "minecraft:calcite|1",
            "minecraft:smooth_basalt|1"
        ]
    ],
    [
        "cobblestone",
        "minecraft:bedrock",
        [
            "minecraft:granite|1",
            "minecraft:diorite|1",
            "minecraft:andesite|1",
            "minecraft:cobbled_deepslate|1"
        ]
    ],
    [
        "stone",
        "minecraft:bedrock",
        [
            "minecraft:granite|1",
            "minecraft:diorite|1",
            "minecraft:andesite|1",
            "minecraft:deepslate|1"
        ]
    ],
    [
        "cobblestone",
        "minecraft:end_stone",
        [
            "minecraft:end_stone"
        ]
    ],
    [
        "cobblestone",
        "minecraft:deepslate",
        [
            "minecraft:cobbled_deepslate"
        ]
    ],
    [
        "stone",
        "minecraft:deepslate",
        [
            "minecraft:deepslate"
        ]
    ],
    [
        "cobblestone",
        "minecraft:cobbled_deepslate",
        [
            "minecraft:cobbled_deepslate"
        ]
    ],
    [
        "stone",
        "minecraft:cobbled_deepslate",
        [
            "minecraft:deepslate"
        ]
    ]
]
