name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan Andersson"
version = "4.3.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b65bab2b5b6a0799c32d6e2d3957c74d5d8fb56f73f8683230f47235c3c10eb"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
