name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan Andersson"
version = "4.3.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83169c51dfada80f4bf32dfce4512e7f97ade105886382971f1d7c2de7c8f7a6"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
