name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan Andersson"
version = "4.3.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "146e90b26e87bcfcf02729ba87432486e9d6a2796c46d3e7f3fbcf597b73304c"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
