name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan ???"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da45b1337a588e913280e0d12c90d0efb39254021c47a1eb9c24bb86a6e67a9f"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
