name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan Andersson"
version = "4.3.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16881aab91e56b6c10b625d83d01626740513aedb330f98616a2220a7d926137"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
