name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan ???"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d2b265bd018a90ec7946fc7080a0f2d76b9fc220d2b701bdc1072c1d93bdb4d"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
