name = "Thonks & Stonks"
author = "Tristan Maat, Will Frost, Johan ???"
version = "4.1.0-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8995ad873fe1a8907b7015cfe58c940abec5116a1e9505b492979a4b16a22c51"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
